package view.sun;

import controller.ResultProxy;
import model.ViewContent;
import other.entity.api.Result;
import other.entity.api.Trading;
import other.utils.SwingUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;

/**
 * Created by Yuquan Zou on 2015/12/26.
 */
public class buyAndSell {
    private JPanel content;
    private JLabel L1;
    private JRadioButton a25RadioButton;
    private JRadioButton a50RadioButton;
    private JRadioButton a75RadioButton;
    private JRadioButton a100RadioButton;
    private JLabel L2;
    private JRadioButton buy;
    private JRadioButton sell;
    private JRadioButton shijia;
    private JRadioButton weituo;
    private JLabel L3;
    private JTextField textField1;
    private JButton submit;
    private JRadioButton othersradion;
    private JTextField textField2;
    private JLabel L42;
    private JTextArea textArea1;
    private JScrollPane jsc;
    private String value[] = new String[5];

    public buyAndSell(final ViewContent viewContent) {
        JFrame jFrame = new JFrame("交易");
        jFrame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        jFrame.setContentPane(this.content);
        SwingUtils.window_centered(jFrame);
        jFrame.setVisible(true);
        ActionListener listener1 = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JRadioButton jRadioButton = (JRadioButton) e.getSource();
                if (jRadioButton.getText().equals("买入")) {
                    value[1] = "0";
                } else {
                    value[1] = "1";
                }
            }
        };
        buy.addActionListener(listener1);
        sell.addActionListener(listener1);
        ActionListener listener2 = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JRadioButton jRadioButton = (JRadioButton) e.getSource();
                if (jRadioButton.getText().equals("委托")) {
                    value[2] = "0";
                    textField1.setEnabled(true);
                } else {
                    value[2] = "1";
                    textField1.setEnabled(false);
                }
            }
        };
        shijia.addActionListener(listener2);
        weituo.addActionListener(listener2);
        submit.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Result result = viewContent.getApiOperation().buyAndSell(value);
                if (result != null) {
                    Trading trading = ResultProxy.proxy(result, Trading.class, textArea1);
                    SwingUtils.appendText(textArea1, trading.getResult() + "订单Id为：" + trading.getId());
                }
            }
        });
        othersradion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                textField2.setEnabled(true);
                value[0] = textField2.getText();
            }
        });
        ActionListener listener = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JRadioButton radioButton = (JRadioButton) e.getSource();
                value[0] = (radioButton.getText().replace("%", ""));
                textField2.setEnabled(false);
            }
        };
        a25RadioButton.addActionListener(listener);
        a50RadioButton.addActionListener(listener);
        a75RadioButton.addActionListener(listener);
        a100RadioButton.addActionListener(listener);
        textField2.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                super.focusLost(e);
                JTextField tf = (JTextField) e.getSource();
                value[0] = tf.getText();
            }
        });
        textField1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                super.focusLost(e);
                JTextField tf = (JTextField) e.getSource();
                value[3] = tf.getText();
            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        content = new JPanel();
        content.setLayout(new GridBagLayout());
        L1 = new JLabel();
        L1.setText("交易百分比:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        content.add(L1, gbc);
        a25RadioButton = new JRadioButton();
        a25RadioButton.setHideActionText(false);
        a25RadioButton.setSelected(false);
        a25RadioButton.setText("25%");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(a25RadioButton, gbc);
        a50RadioButton = new JRadioButton();
        a50RadioButton.setText("50%");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(a50RadioButton, gbc);
        a75RadioButton = new JRadioButton();
        a75RadioButton.setText("75%");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(a75RadioButton, gbc);
        a100RadioButton = new JRadioButton();
        a100RadioButton.setText("100%");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(a100RadioButton, gbc);
        L2 = new JLabel();
        L2.setText("交易类型：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        content.add(L2, gbc);
        buy = new JRadioButton();
        buy.setSelected(false);
        buy.setText("买入");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(buy, gbc);
        sell = new JRadioButton();
        sell.setText("卖出");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(sell, gbc);
        L3 = new JLabel();
        L3.setText("交易方式：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        content.add(L3, gbc);
        shijia = new JRadioButton();
        shijia.setHideActionText(false);
        shijia.setText("市价");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(shijia, gbc);
        weituo = new JRadioButton();
        weituo.setSelected(false);
        weituo.setText("委托");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(weituo, gbc);
        textField1 = new JTextField();
        textField1.setEnabled(false);
        textField1.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        content.add(textField1, gbc);
        othersradion = new JRadioButton();
        othersradion.setText("其他");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        content.add(othersradion, gbc);
        textField2 = new JTextField();
        textField2.setEnabled(false);
        textField2.setPreferredSize(new Dimension(35, 25));
        textField2.setText("0");
        textField2.setVisible(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.BOTH;
        content.add(textField2, gbc);
        jsc = new JScrollPane();
        jsc.setAutoscrolls(true);
        jsc.setHorizontalScrollBarPolicy(30);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 6;
        gbc.gridheight = 5;
        gbc.fill = GridBagConstraints.BOTH;
        content.add(jsc, gbc);
        textArea1 = new JTextArea();
        textArea1.setAutoscrolls(true);
        textArea1.setEditable(false);
        textArea1.setRows(6);
        jsc.setViewportView(textArea1);
        L42 = new JLabel();
        L42.setText("交易状态：");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridheight = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        content.add(L42, gbc);
        submit = new JButton();
        submit.setText("确定");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        content.add(submit, gbc);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(buy);
        buttonGroup.add(sell);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(shijia);
        buttonGroup.add(weituo);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(a25RadioButton);
        buttonGroup.add(a50RadioButton);
        buttonGroup.add(a75RadioButton);
        buttonGroup.add(a100RadioButton);
        buttonGroup.add(othersradion);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return content;
    }
}
