package view.sun;

import controller.APIOperation;
import model.ViewContent;
import other.entity.FecUser;
import other.entity.Result;
import other.utils.SwingUtils;
import service.LoginService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * Created by Yuquan Zou on 2015/12/24.
 */
public class login {
    private JTextField username;
    private JButton login;
    private JLabel user;
    private JPanel loginJpanel;


    public login(final ViewContent viewContent) {
        final LoginService loginService = viewContent.getApplicationContext().getBean(LoginService.class);
        final JFrame frame = viewContent.getFrame();
        username.setText("13299266512");
        login.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Result<List<FecUser>> bool = loginService.validate(username.getText());
                if (!bool.isResult()) {
                    JOptionPane.showMessageDialog(null, "没有此用户", "警告", JOptionPane.WARNING_MESSAGE);
                } else {
                    APIOperation apiOperation = viewContent.getApiOperation();
                    apiOperation.setUserId(username.getText().trim());
                    Real_data real_data = new Real_data(viewContent);
                    SwingUtils.window_replace(frame, real_data.getContent(), "main");
                }
            }

        });
    }

    public JPanel getLoginJpanel() {
        return loginJpanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        loginJpanel = new JPanel();
        loginJpanel.setLayout(new GridBagLayout());
        user = new JLabel();
        user.setText("用户名：");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        loginJpanel.add(user, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        loginJpanel.add(spacer1, gbc);
        username = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 123;
        loginJpanel.add(username, gbc);
        login = new JButton();
        login.setText("登陆");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        loginJpanel.add(login, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return loginJpanel;
    }
}
